[package]
name = "emote-psb"
version = "0.1.0"
authors = ["storycraft <storycraft@pancake.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
byteorder = "1.3.4"
encoding = "0.2.33"
adler = "1.0.1"